name: 01 - Building Blocks
on:
  push:
  workflow_dispatch:

jobs:
  echo-heelo:
    runs-on: ubuntu-latest
    steps:
      -name: Helo World step
       run: echo Helo World!
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      -name: Failed step
       run: echo Goodbye!
        
      -name: Multi-line bash
       run: |
        echo "I am"
        echo "a multi-line"
        echo "script." 