name: Intro - YAML Syntax

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/intro-yaml-syntax.yml'
jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job will be run first."
  fanout1:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - run: echo "This job will run after the initial job, in parallel with fanout2."
  fanout2:
    runs-on: ubuntu-latest
    needs: initial
    steps:
      - run: echo "This job will run after the initial job, in parallel with fanout1."
  fanout3:
    runs-on: ubuntu-latest
    needs: fanout1
    steps:
      - run: echo "This job will run after the initial job, in parallel with fanout2."
  fanin:
    runs-on: ubuntu-latest
    needs: [fanout1, fanout2]
    steps:
      - run: echo "This job will run after fanout1 and fanout2 have finished."
  final:
    runs-on: ubuntu-latest
    needs: fanin
    steps:
      - run: echo "This job will run last, after all other jobs have completed."
      - run: echo "The workflow is now complete!"
      - name: Adding Markdown
        run: echo "### YAML Syntax Example Completed! :rocket:" >> "$GITHUB_STEP_SUMMARY"
