name: JS Static Web App Deploy to Azure

on:
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: 'src/javascript/simple-spa'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use version that matches your local dev env

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build the app
        run: npm run build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.JS_STATIC_WEB_APP_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: ${{ env.WORKING_DIRECTORY }}
          output_location: 'dist'
