name: Python Flask App Docker Deploy to Azure

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/python-flask-app-docker-deploy-to-azure.yml'
      - 'src/python/flask-app/**'

env:
  AZURE_WEBAPP_NAME: app-flask-webapp
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/flask-app
  WORKING_DIRECTORY: 'src/python/flask-app'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.WORKING_DIRECTORY }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Deploy to Azure Web App (Container)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.IMAGE_NAME }}:latest
