name: Python Flask App Deploy to Azure
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/python-flask-app-deploy-to-azure.yml'
      - 'src/python/flask-app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: src/python/flask-app

      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: <YOUR_WEB_APP_NAME>
      #     slot-name: Production
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     package: .
