name: Reusable Workflow Echo Caller

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/reusable-workflow-echo-caller.yml'
jobs:
  say-hello:
    uses: ./.github/workflows/reusable-workflow-echo.yml
    with:
      my-input: 'Hello, world!'
  say-goodbye:
    #uses: https://github.com/prasadhonrao/github-actions-workshop-shared-repo/blob/main/.github/workflows/deploy.yml
    uses: ./.github/workflows/reusable-workflow-echo.yml
    with:
      my-input: 'Goodbye!'
