name: Runner - Matrix

on: workflow_dispatch

jobs:
  display:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Display Environment Variables
        run: printenv | sort
        shell: bash
