name: Terraform - Simple Web App Deployment

on:
  workflow_dispatch:
    inputs:
      webapp_name:
        description: 'Name of the Azure Web App'
        required: true
        default: 'my-webapp'
      resource_group_name:
        description: 'Name of the Azure Resource Group'
        required: true
        default: 'my-resource-group'
      publish_dir:
        description: 'App directory to deploy (e.g., src, dist, build)'
        required: true
        default: 'src/terraform/simple-webapp/app'

jobs:
  infra:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/terraform/simple-webapp/iac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse Azure credentials
        id: auth
        run: |
          echo '${{ secrets.AZURE_SERVICE_PRINCIPAL }}' > azurecreds.json
          echo "ARM_CLIENT_ID=$(jq -r .clientId azurecreds.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azurecreds.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azurecreds.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId azurecreds.json)" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="webapp_name=${{ github.event.inputs.webapp_name }}" \
            -var="resource_group_name=${{ github.event.inputs.resource_group_name }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="webapp_name=${{ github.event.inputs.webapp_name }}" \
            -var="resource_group_name=${{ github.event.inputs.resource_group_name }}"

  deploy:
    name: Deploy Web App Code
    runs-on: ubuntu-latest
    needs: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      # Optional build step (for Node.js apps)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.event.inputs.publish_dir }}

      - name: Build app
        run: npm run build --if-present
        working-directory: ${{ github.event.inputs.publish_dir }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ github.event.inputs.webapp_name }}
          slot-name: 'production'
          package: ${{ github.event.inputs.publish_dir }}
